### ISSUE TITLE
Failing CI E2E tests, chrome path not found

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#448]
CI E2E tests are failing for the windows machine. It appears that protractor is unable to find the location of the chrome binary.

Some potentially helpful links:

- https://github.com/angular/protractor/issues/950
- https://stackoverflow.com/questions/41352511/docker-selenium-node-chrome-protractor-can-not-find-chrome-binary

**Comment by Allcharles** [comment]
Error Logs (https://github.com/QutEcoacoustics/workbench-client/runs/1064203990):
```
WARNING in D:\a\workbench-client\workbench-client\node_modules\@vvo\tzdb\lib\getTimeZones.js depends on 'sort-on'. CommonJS or AMD dependencies can cause optimization bailouts.
chunk {main} main.js, main.js.map (main) 1.56 MB [initial] [rendered]
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 148 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 748 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.23 MB [initial] [rendered]
Date: 2020-09-02T23:18:14.005Z - Hash: b46982c4fd650ee07884 - Time: 41206ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
[23:18:14] I/launcher - Running 1 instances of WebDriver
[23:18:14] I/direct - Using ChromeDriver directly...
[23:18:15] E/launcher - unknown error: cannot find Chrome binary
  (Driver info: chromedriver=85.0.4183.38 (9047dbc2c693f044042bbec5c91401c708c7c26a-refs/branch-heads/4183@{#779}),platform=Windows NT 10.0.17763 x86_64)
[23:18:15] E/launcher - WebDriverError: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=85.0.4183.38 (9047dbc2c693f044042bbec5c91401c708c7c26a-refs/branch-heads/4183@{#779}),platform=Windows NT 10.0.17763 x86_64)
    at Object.checkLegacyResponse (D:\a\workbench-client\workbench-client\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (D:\a\workbench-client\workbench-client\node_modules\selenium-webdriver\lib\http.js:509:13)
    at D:\a\workbench-client\workbench-client\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.createSession()
    at Function.createSession (D:\a\workbench-client\workbench-client\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (D:\a\workbench-client\workbench-client\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (D:\a\workbench-client\workbench-client\node_modules\protractor\built\driverProviders\direct.js:77:33)
```

Problem stems from the e2e not being able to find the chrome binary. It appears the default chrome build is now x64 instead of x32, and the protractor library does not know the new path.
